listings_get:
    pattern: /lists/{projectId}
    defaults: { _controller: "WacTechWebBundle:Api:getLists" }
    requirements:
        _format: json
        methods: GET

task_done_put:
    pattern: /task/{id}
    defaults: { _controller: "WacTechWebBundle:Api:doneTask" }
    requirements:
        _format: json
        methods: PATCH

card_api_new:
    pattern: /card/new/{listId}
    defaults: { _controller: "WacTechWebBundle:Api:newCard" }
    requirements:
        _format: json
        methods: POST
