api_listings_get:
    pattern: /lists/{projectId}
    defaults: { _controller: "WacTechWebBundle:Api:getLists" }
    requirements:
        _format: json
        methods: GET

api_task_done:
    pattern: /task/{id}
    defaults: { _controller: "WacTechWebBundle:Api:doneTask" }
    requirements:
        _format: json
        methods: PATCH

api_card_new:
    pattern: /card/new/{listId}
    defaults: { _controller: "WacTechWebBundle:Api:newCard" }
    requirements:
        _format: json
        methods: POST

api_card_remove:
    pattern: /card/{id}/delete
    defaults: { _controller: "WacTechWebBundle:Api:removeCard" }
    requirements:
        _format: json
        methods: DELETE

api_task_remove:
    pattern: /task/{id}/delete
    defaults: { _controller: "WacTechWebBundle:Api:removeTask" }
    requirements:
        _format: json
        methods: DELETE

api_task_new:
    pattern: /task/new/{cardId}
    defaults: { _controller: "WacTechWebBundle:Api:newTask" }
    requirements:
        _format: json
        methods: POST
