listing:
    path:     /
    defaults: { _controller: "WacTechWebBundle:Listing:index" }

listing_show:
    path:     /{id}/show
    defaults: { _controller: "WacTechWebBundle:Listing:show" }

listing_new:
    path:     /new
    defaults: { _controller: "WacTechWebBundle:Listing:new" }

listing_create:
    path:     /create
    defaults: { _controller: "WacTechWebBundle:Listing:create" }
    methods:  POST

listing_edit:
    path:     /{id}/edit
    defaults: { _controller: "WacTechWebBundle:Listing:edit" }

listing_update:
    path:     /{id}/update
    defaults: { _controller: "WacTechWebBundle:Listing:update" }
    methods:  [POST, PUT]

listing_delete:
    path:     /{id}/delete
    defaults: { _controller: "WacTechWebBundle:Listing:delete" }
    methods:  [POST, DELETE]
