Accounting\AccountBundle\Entity\Account:
    type: entity
    table: null
    repositoryClass: Accounting\AccountBundle\Entity\AccountRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
